<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>ZedEshop_Microservices</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="ApiGateways\YarpApiGateway\" />
      <Folder Include="BuildingBlocks\" />
      <Folder Include="Services\" />
    </ItemGroup>

</Project>
